{% set version = "0.3.9" %}

package:
  name: thriftpy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/thriftpy/thriftpy-{{ version }}.tar.gz
  sha256: 309e57d97b5bfa01601393ad4f245451e989d6206a59279e56866b264a99796d
  patches:
    - fix-parse-windows.patch

build:
  number: 1002
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - ply >=3.4,<4.0
    # Cython extensions not enabled on windows
    - cython  # [not win]

  run:
    - python
    - ply >=3.4,<4.0

test:
  imports:
    - thriftpy
    - thriftpy.contrib
    - thriftpy.contrib.tracking
    - thriftpy.parser
    - thriftpy.protocol
    - thriftpy.transport
    - thriftpy.transport.buffered
    - thriftpy.transport.framed
    - thriftpy.transport.memory
    # Cython extensions not enabled on windows
    - thriftpy.protocol.cybin  # [not win]
  commands:
    - pip check
  requires:
    - pip
    - tornado >=4.0,<5.0

about:
  home: https://thriftpy.readthedocs.org/
  license: MIT
  license_file: LICENSE
  summary: 'Pure python implementation of Apache Thrift.'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - mrocklin
